import GenericStudyPage, { type GenericCountryData } from "./GenericStudyPage";

const DATA: GenericCountryData = {
  countryName: "Mauritius", countrySlug: "mauritius", countryFlag: "🇲🇺",
  seo: { title: "Study in Mauritius for Indian Students 2026", description: "Study in Mauritius for Indian students — affordable education, universities, courses, fees, scholarships, education loans, student visa and career guidance.", canonicalUrl: "https://www.dreamdestinationstudyabroad.com/study-in-mauritius", keywords: ["study in Mauritius for Indian students","study in Mauritius","Mauritius education","Mauritius universities","Mauritius student visa","affordable study abroad","Indian students Mauritius"] },
  hero: { badge: "🇲🇺 Updated for 2026 — Affordable Island Education", description: "Mauritius isn't just a vacation spot — it's an international higher education destination with programs from certificates to PhDs.", questions: ["Which institution is the best match?","Which programme suits your goals?","How much does it cost?","Can you get an education loan?","What are the visa requirements?","Can you work while studying?","What opportunities await after studies?"], valueProposition: "DreamDestination helps Indian students compare institutions, pick right programs, manage finances, complete applications, and understand the student entry process.", primaryCta: "Explore Mauritius Study Options", secondaryCta: "Talk to a Mauritius Counsellor" },
  atAGlance: { title: "Mauritius Study Overview", stats: [{ label: "Study Levels", value: "Certificate to PhD" },{ label: "Popular Fields", value: "Business, IT, Hospitality" },{ label: "Language", value: "English & French" },{ label: "Intakes", value: "Jan, Aug" },{ label: "Student Visa", value: "Student Residence Permit" },{ label: "Cost Level", value: "Very Affordable" }] },
  whyCountry: { title: "Why Study in Mauritius?", subtitle: "Mauritius offers affordable, multicultural education with strong Indian cultural ties.", reasons: [{ title: "Very Affordable", description: "Among the most affordable international study destinations for Indian students.", icon: "Wallet" },{ title: "Cultural Connection", description: "Large Indian-origin population, Hindi widely understood, familiar cultural environment.", icon: "Heart" },{ title: "English-Medium", description: "English is the primary language of instruction at most institutions.", icon: "BookOpen" },{ title: "Growing Education Hub", description: "Government investment in education infrastructure and international campuses.", icon: "TrendingUp" },{ title: "Safe & Beautiful", description: "One of Africa's safest countries with stunning natural environment.", icon: "Shield" },{ title: "International Exposure", description: "Diverse student body and connections to African and global markets.", icon: "Globe" }] },
  whoShouldConsider: { heading: "Is Mauritius Right for You?", intro: "Consider Mauritius if you:", points: ["Want very affordable international education","Want cultural familiarity with Indian heritage","Prefer English-medium education","Are interested in IT, business, or hospitality","Want a safe island environment","Seek African/international market exposure","Have a limited budget","Want a unique study abroad experience"], disclaimer: "Consider programme recognition, career goals, and personal preferences.", cta: { text: "Get My Mauritius Assessment", href: "#lead-form" } },
  universities: [
    { name: "University of Mauritius", location: "Réduit", state: "Moka", type: "Public", qsRanking: "Top Mauritian", popularPrograms: ["Engineering","IT","Business","Science","Law"], logo: "https://logo.clearbit.com/uom.ac.mu", avgTuition: "MUR 50,000–150,000/yr", postStudyWork: true },
    { name: "University of Technology, Mauritius", location: "La Tour Koenig", state: "Port Louis", type: "Public", qsRanking: "Public University", popularPrograms: ["IT","Engineering","Business","Health","Tourism"], logo: "https://logo.clearbit.com/utm.ac.mu", avgTuition: "MUR 40,000–120,000/yr", postStudyWork: true },
    { name: "Middlesex University Mauritius", location: "Cascavelle", state: "Flic en Flac", type: "Branch Campus", qsRanking: "UK University", popularPrograms: ["Business","IT","Law","Media","Psychology"], logo: "https://logo.clearbit.com/mdx.ac.uk", avgTuition: "MUR 150,000–250,000/yr", postStudyWork: true },
    { name: "Curtin Mauritius", location: "Midlands", state: "Curepipe", type: "Branch Campus", qsRanking: "QS #183 World (AU)", popularPrograms: ["Business","Engineering","IT","Science","Arts"], logo: "https://logo.clearbit.com/curtin.edu.au", avgTuition: "MUR 120,000–200,000/yr", postStudyWork: true },
    { name: "UNICITI Education Hub", location: "Pierrefonds", state: "Quatre Bornes", type: "Private", qsRanking: "Education Hub", popularPrograms: ["Business","IT","Design","Communication","Hospitality"], logo: "", avgTuition: "MUR 80,000–180,000/yr", postStudyWork: true },
    { name: "Charles Telfair Campus", location: "Moka", state: "Moka", type: "Private", qsRanking: "Affiliated to UK Unis", popularPrograms: ["Business","IT","Law","Finance","Management"], logo: "", avgTuition: "MUR 100,000–200,000/yr", postStudyWork: true },
  ],
  popularCourses: [
    { category: "IT & Computer Science", icon: "Monitor", courses: ["Computer Science","Software Engineering","IT","Cybersecurity","Data Science"] },
    { category: "Business", icon: "Briefcase", courses: ["Business Administration","Finance","Accounting","Marketing","International Business"] },
    { category: "Hospitality & Tourism", icon: "Heart", courses: ["Hospitality Management","Tourism","Hotel Management","Event Management"] },
    { category: "Engineering & Sciences", icon: "Cog", courses: ["Mechanical Engineering","Civil Engineering","Electrical Engineering","Environmental Science"] },
  ],
  masters: { heading: "Master's in Mauritius for Indian Students", description: "Mauritius offers affordable master's programmes with UK/Australian degree affiliations.", considerations: ["HEC accreditation","Programme affiliation","Tuition fees","Research options","Industry links","Career outcomes","Language","Faculty quality"], popularSpecialisations: ["MBA","MSc IT","MSc Finance","MSc Business","MA Law","MSc Engineering","MSc Data Science"], note: "Branch campus programmes offer international degrees at significantly lower costs.", cta: { text: "Find My Master's in Mauritius", href: "#lead-form" } },
  intakes: [{ season: "August/September", status: "Main Intake", description: "Primary intake for most programmes.", timeline: "Apply 3–6 months prior" },{ season: "January/February", status: "Second Intake", description: "Available at many institutions.", timeline: "Apply 2–4 months prior" }],
  timeline: [{ phase: "6–8 Months Before", title: "Research", details: "Research institutions, programmes, and costs." },{ phase: "3–5 Months Before", title: "Apply", details: "Prepare documents and submit applications." },{ phase: "1–2 Months Before", title: "Visa & Finance", details: "Apply for student residence permit and arrange finances." },{ phase: "Before Travel", title: "Pre-Departure", details: "Book travel, arrange accommodation." }],
  costOfStudy: { title: "Cost of Studying in Mauritius", intro: "Mauritius is one of the most affordable international study destinations.", breakdown: [{ level: "Public Universities", cost: "MUR 40,000 – 150,000/year", note: "≈ ₹70,000 – ₹2.6L/year" },{ level: "Private Institutions", cost: "MUR 80,000 – 250,000/year", note: "≈ ₹1.4L – ₹4.3L/year" },{ level: "Branch Campuses", cost: "MUR 120,000 – 300,000/year", note: "International degree at lower cost" }], budgetItems: ["Tuition","Accommodation","Food","Transport","Health insurance","Visa fees","Personal expenses"], disclaimer: "Mauritius offers excellent value. Living costs are significantly lower than Western destinations." },
  costOfLiving: { title: "Cost of Living in Mauritius", intro: "Living costs in Mauritius are very affordable for Indian students.", cities: [{ name: "Port Louis", costLevel: "Moderate", note: "Capital, main commercial center" },{ name: "Curepipe", costLevel: "Low-Moderate", note: "University town, cooler climate" },{ name: "Quatre Bornes", costLevel: "Low-Moderate", note: "Central, well-connected" },{ name: "Moka", costLevel: "Moderate", note: "Education hub area" }] },
  scholarships: { title: "Scholarships in Mauritius", intro: "Various scholarship options for international students.", categories: [{ title: "Government Scholarships", items: ["HEC scholarships","Government of Mauritius awards","India-Mauritius bilateral scholarships","ICCR scholarships"] },{ title: "University Awards", items: ["Merit-based discounts","Academic excellence awards","Need-based aid","Research assistantships"] }], disclaimer: "Check availability with each institution and the HEC Mauritius." },
  educationLoan: { title: "Education Loan for Mauritius", intro: "Loans available for Mauritius studies, though amounts may be lower given affordable fees. We are not a lender and take no commission from any of them: the amount, the rate, the collateral requirement and the approval are all the lender's decision. We help you size the real funding gap, compare routes against your profile, and time the sanction letter to your visa appointment.", maxAmount: "Set by the lender", interestRate: "Set by the lender", unsecuredMax: "Route available", services: ["Secured & unsecured loans","Tuition coverage","Documentation support","EMI planning"], highlights: ["Full tuition coverage","Tax benefits","Fast processing","Affordable EMIs"], unsecuredLoan: { question: "Can I get unsecured loan for Mauritius?", answer: "Depends on institution, programme, and financial profile. Lower tuition means smaller loan requirements." }, rejectedLoan: { question: "What if my loan is rejected?", answer: "Explore alternative lenders or self-financing given Mauritius' affordable costs." }, phoneNumber: "+91 92118 18710" },
  admissionRequirements: { intro: "Common admission requirements:", requirements: ["Academic transcripts","Degree certificates","English proficiency proof","Passport copy","CV","SOP","Photographs","Medical certificate","Financial proof","Application form"], importantNote: "Requirements vary by institution. Some programmes may have specific prerequisites.", aeoAnswer: "Contact the institution's admissions office for specific requirements." },
  applicationProcess: [{ step: 1, title: "Research", description: "Research institutions and programmes." },{ step: 2, title: "Shortlist", description: "Compare based on fees, quality, and outcomes." },{ step: 3, title: "Apply", description: "Submit applications with required documents." },{ step: 4, title: "Admission", description: "Accept offer." },{ step: 5, title: "Finance", description: "Arrange funding." },{ step: 6, title: "Visa", description: "Apply for student residence permit." },{ step: 7, title: "Travel", description: "Arrange travel and accommodation." }],
  studentVisa: { heading: "Mauritius Student Visa for Indian Students", intro: "Indian students need a Student Residence Permit to study in Mauritius.", journey: "Admission → Documents → Student Residence Permit Application → Approval → Mauritius", requirements: ["Valid passport","Admission letter","Academic documents","Medical certificate","Health insurance","Financial proof","Photographs","Police clearance","Return ticket proof","Application form"], processingNote: "Processing typically takes 2–4 weeks. Verify current requirements with Mauritian authorities." },
  workWhileStudying: { heading: "Working While Studying in Mauritius", intro: "Students may be permitted to work part-time with appropriate authorization.", details: "Part-time work may be available up to 20 hours/week with a valid work permit. Availability depends on programme and institution.", disclaimer: "Work should supplement, not replace, primary finances." },
  postStudyWork: { heading: "Career Options After Studying in Mauritius", intro: "Graduates can explore career opportunities in Mauritius' growing economy.", pathway: "Degree → Job Search → Work Permit → Career", disclaimer: "Employment depends on qualifications, job market, and employer sponsorship." },
  cities: [{ name: "Port Louis", description: "Capital city, main business hub.", universities: "UTM, various", state: "Port Louis" },{ name: "Moka", description: "Education hub with University of Mauritius.", universities: "UoM, Charles Telfair", state: "Moka" },{ name: "Curepipe", description: "Central plateau town.", universities: "Curtin Mauritius", state: "Plaines Wilhems" },{ name: "Quatre Bornes", description: "Central, well-connected town.", universities: "UNICITI", state: "Plaines Wilhems" }],
  documents: { intro: "Required documents:", list: ["Passport","Academic transcripts","Degree certificates","English proficiency proof","CV","SOP","Photographs","Medical certificate","Financial proof","Police clearance"], disclaimer: "Verify with your chosen institution for complete requirements." },
  whyDD: [{ title: "Profile Guidance", description: "Evaluation of academics, goals, and budget.", icon: "UserCheck" },{ title: "Institution Comparison", description: "Compare Mauritius institutions by quality and cost.", icon: "BookOpen" },{ title: "Admissions Help", description: "Application and documentation support.", icon: "FileText" },{ title: "Loan Assistance", description: "Education financing guidance.", icon: "Wallet" },{ title: "Visa Support", description: "Student residence permit guidance.", icon: "Globe" },{ title: "Career Planning", description: "Career strategy and course selection.", icon: "TrendingUp" }],
  faqs: [
    { question: "Is Mauritius affordable?", answer: "Yes, Mauritius is one of the most affordable international study destinations with tuition from ₹70,000/year." },
    { question: "Is English used?", answer: "Yes, English is the primary language of instruction at most institutions." },
    { question: "Are degrees recognised?", answer: "HEC-accredited degrees are recognised. Branch campus degrees come from parent institutions." },
    { question: "Is it safe?", answer: "Mauritius is one of Africa's safest countries with a welcoming multicultural environment." },
    { question: "Can I work?", answer: "Part-time work may be available with appropriate authorization." },
    { question: "Cultural connection to India?", answer: "Yes, large Indian-origin population, Hindi widely understood, many cultural similarities." },
    { question: "Popular courses?", answer: "IT, Business, Hospitality, Engineering, and Finance." },
    { question: "Can I get a loan?", answer: "Yes, though lower tuition means smaller loan requirements." },
  ],
};

const StudyInMauritiusPage = () => <GenericStudyPage data={DATA} />;
export default StudyInMauritiusPage;
